name: CI 
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
# make sure steps are run in a login shell to support Lmod modules 
defaults:
  run:
    shell: bash -l {0}
jobs: 
  style:
    runs-on: ubuntu-20.04
    container:
      image: jenilut/cse380_team2
      options: --user 1001 --privileged
    name: CI test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: module load boost gsl petsc && module load phdf5 && autoreconf -f -i && ./configure CC=mpicc CXX="mpicxx -std=c++17 -O3" FC=mpif90 --with-grvy=/usr/local/ --with-hdf5=$HDF5_DIR --with-petsc=$PETSC_DIR
      - name: Test
        run: module load boost gsl petsc && module load phdf5 && make check
